# Generated by Django 5.2.4 on 2025-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('descp', models.CharField(blank=True, null=True, verbose_name=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('priority', models.TextField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')])),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
