# Generated by Django 5.2.4 on 2025-08-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
