# Generated by Django 5.2.4 on 2025-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=10, null=True),
        ),
    ]
